export const CREATE_NOTE = 'CREATE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';


export const CHANGE_INPUT_SUM = 'CHANGE_INPUT_SUM';
export const CHANGE_INPUT_TEXT = 'INPUT_TEXT';
export const EDIT_INPUT = 'EDIT_INPUT_TEXT';
export const SAVE_INPUT = 'SAVE_INPUT_TEXT';
export const CANCEL_INPUT = 'CANCEL_INPUT';


export const CHANGE_VALUE_FILTER = 'CHANGE_VALUE_FILTER';
export const CHANGE_DATA_FILTER = 'CHANGE_DATA_FILTER';